import logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚠️ MEDICAL DISCLAIMER: The suggestions and roadmaps generated by Glowup Coach "
    "are for aesthetic, educational, and general wellness purposes only. They do not constitute "
    "professional medical advice, diagnosis, or treatment. Always consult with a licensed dermatologist, "
    "orthodontist, or cosmetic surgeon before starting any new treatments, active skincare regimes, "
    "or corrective physical exercises."
)

class GuidanceGenerator:
    @staticmethod
    def generate_roadmap(scores: Dict[str, float], gender: str) -> Dict[str, Any]:
        """
        Generates a custom 4-week roadmap combining the user's specific weekly focus actions 
        with a fully populated 28-day interactive checklist.
        """
        # Exclude Harmony and Golden_Ratio from feature calculation to isolate weak features
        feature_scores = {k: v for k, v in scores.items() if k not in ["Harmony", "Golden_Ratio"]}
        sorted_features = sorted(feature_scores.items(), key=lambda item: item[1])
        
        weak_features = [feature for feature, val in scores.items() if val < 70]
        weak_features.sort(key=lambda f: scores[f])
        
        # We ensure at least 2 weakest features are identified
        weakest_1 = sorted_features[0][0]
        weakest_2 = sorted_features[1][0]
        
        # User defined focus details
        week1_actions = [
            "Daily facial yoga to improve muscle symmetry",
            "Use gua sha or jade roller for de-puffing and contour",
            "Ensure even lighting & posture during photos"
        ]
        
        week2_actions = [
            "Eye exercises (e.g., palming, focus shifting) to reduce strain",
            "Use caffeine serums to reduce dark circles",
            "Shape brows to complement your face shape"
        ]
        
        week3_actions = [
            "Facial resistance exercises for jawline (e.g., chin lifts)",
            "Hydrate and exfoliate lips for natural plumpness",
            "Consider facial massage for lymphatic drainage"
        ]
        
        week4_actions = [
            "Learn makeup contouring techniques for nose slimming",
            "Practice full-face facial relaxation (reduce tension)",
            "Maintain a balanced diet to reduce facial bloating"
        ]
        
        # Gender-specific actions
        if gender == "female":
            week2_actions.append("Try lash lifting and brow lamination for open eyes")
            week3_actions.append("Use lip liner to slightly overdraw for better proportion")
        else:
            week2_actions.append("Keep brows well-groomed but natural for masculine look")
            week3_actions.append("Jawline chewing exercises (e.g., mastic gum)")

        # Compile structured 4-week calendar for React timeline
        roadmap = []
        
        # Week 1
        roadmap.append({
            "week": 1,
            "theme": "Skin & symmetry basics",
            "goals": week1_actions,
            "days": [
                {"day": 1, "task": "Begin daily facial yoga to address facial muscle symmetry.", "demo": "Face Yoga"},
                {"day": 2, "task": "Apply cold compression and roll with a jade roller to reduce puffiness.", "demo": "Jade Roller Sweep"},
                {"day": 3, "task": "Check posture alignment in mirror: keep chin parallel to floor.", "demo": "Posture Alignment"},
                {"day": 4, "task": "Integrate 3 minutes of Gua Sha along the cheekbones.", "demo": "Gua Sha Contour"},
                {"day": 5, "task": "Practice symmetry exercises: smile evenly using a mirror to trace.", "demo": "Symmetry Smile"},
                {"day": 6, "task": "Perform neck stretch: release muscle tension pulling the jaw.", "demo": "Neck Stretch"},
                {"day": 7, "task": "Record week 1 summary profile; measure overall baseline comfort.", "demo": "Progress log"}
            ]
        })
        
        # Week 2
        roadmap.append({
            "week": 2,
            "theme": "Eye area enhancement",
            "goals": week2_actions,
            "days": [
                {"day": 8, "task": "Introduce targeted eye exercises: practice palming and focus shifting.", "demo": "Focus Shifting"},
                {"day": 9, "task": "Apply caffeine-infused serums morning and night under eyes.", "demo": "Serum Application"},
                {"day": 10, "task": "Groom and shape eyebrows to lift the orbital structure.", "demo": "Brow Shaping"},
                {"day": 11, "task": "Gender specific action: " + (week2_actions[-1]), "demo": "Brow Grooming"},
                {"day": 12, "task": "Limit device screen time before bed to prevent orbital strain.", "demo": "Blue light block"},
                {"day": 13, "task": "Perform soft tapping massage around the eye socket bone.", "demo": "Orbital Massage"},
                {"day": 14, "task": "Take week 2 progress photo; check changes in eye circles.", "demo": "Progress log"}
            ]
        })
        
        # Week 3
        roadmap.append({
            "week": 3,
            "theme": "Lips and jawline definition",
            "goals": week3_actions,
            "days": [
                {"day": 15, "task": "Perform facial resistance exercises for the jawline (e.g. chin lifts).", "demo": "Jawline Lift"},
                {"day": 16, "task": "Exfoliate lips with sugar scrub; apply hydration balm.", "demo": "Lip Scrub"},
                {"day": 17, "task": "Perform a 5-minute lymphatic drainage massage along the jaw border.", "demo": "Lymph Drainage"},
                {"day": 18, "task": "Gender specific action: " + (week3_actions[-1]), "demo": "Jaw / Lip Sculpting"},
                {"day": 19, "task": "Rest tongue flat against the roof of the mouth (mewing posture).", "demo": "Tongue press"},
                {"day": 20, "task": "Stretch the platysma neck muscle by looking upward and swallowing.", "demo": "Platysma stretch"},
                {"day": 21, "task": "Check jaw symmetry during chewing; balance bite equally.", "demo": "Bilateral Chew"}
            ]
        })
        
        # Week 4
        roadmap.append({
            "week": 4,
            "theme": "Nose contour and overall harmony",
            "goals": week4_actions,
            "days": [
                {"day": 22, "task": "Learn aesthetic makeup contouring techniques for nose bridge slimming.", "demo": "Nose Contour"},
                {"day": 23, "task": "Practice full-face relaxation exercises to release deep muscle tension.", "demo": "Muscle Release"},
                {"day": 24, "task": "Reduce daily sodium intake to prevent facial water retention.", "demo": "Sodium audit"},
                {"day": 25, "task": "Perform sinus pressure points massage next to nose wings.", "demo": "Acupressure drainage"},
                {"day": 26, "task": "Combine eye exercises and jawline contouring into a quick routine.", "demo": "Combo Routine"},
                {"day": 27, "task": "Perform complete posture and shoulder alignment check.", "demo": "Spinal posture"},
                {"day": 28, "task": "Perform your final 30-second Face Scan to assess your glowup progress!", "demo": "Final scan"}
            ]
        })
        
        # Format weak feature details
        focus_areas = []
        for feature in [weakest_1, weakest_2]:
            focus_areas.append({
                "feature": feature,
                "score": scores.get(feature, 70.0),
                "focus": f"Improve {feature} aesthetics using targeted exercises.",
                "tips": [f"Regularly exercise the {feature} area.", "Stay consistent with daily stretches."],
                "demos": [{"title": f"{feature} Yoga", "desc": "Custom motion target."}]
            })

        return {
            "disclaimer": DISCLAIMER,
            "weakest_features": weak_features,
            "focus_areas": focus_areas,
            "roadmap": roadmap
        }
